[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  #[[relaychain.nodes]]
  #name = "charlie"
  #validator = true

  #[[relaychain.nodes]]
  #name = "dave"
  #validator = true

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
cumulus_based = true

  [[parachains.collators]]
  name = "asset-hub-collator1"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]
  ws_port = 9910

[[parachains]]
id = 2000
chain = "shibuya-dev"
cumulus_based = true

  [[parachains.collators]]
  name = "astar-collator1"
  command = "./bin/astar-collator"
  args = ["--log=xcm=trace"]
  ws_port = 9920

[[hrmp_channels]]
sender = 1000
recipient = 2000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 1000
max_capacity = 8
max_message_size = 512
