[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"
default_args = [ "--log=xcm=trace,parachain=debug" ]

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  p2p_port = 39709

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  #[[relaychain.nodes]]
  #name = "dave"
  #validator = true

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
cumulus_based = true

  [[parachains.collators]]
  name = "asset-hub-collator1"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]
  ws_port = 9910
<<<<<<< HEAD:conf/zn-asset-hub-astar.toml
  p2p_port = 39708
=======
  p2p_port = 36647
>>>>>>> 7d796c2 (support injected asset registries for transfer api):config/zn-asset-hub-astar.toml

[[parachains]]
id = 2000
chain = "shibuya-dev"
cumulus_based = true

  [[parachains.collators]]
  name = "astar-collator1"
  command = "./bin/astar-collator"
  args = ["--log=xcm=trace"]
  ws_port = 9920
<<<<<<< HEAD:conf/zn-asset-hub-astar.toml
  p2p_port = 39707
=======
  p2p_port = 40607
>>>>>>> 7d796c2 (support injected asset registries for transfer api):config/zn-asset-hub-astar.toml

[[hrmp_channels]]
sender = 1000
recipient = 2000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 1000
max_capacity = 8
max_message_size = 512
